services:
  app:
    image: node:22.14.0
    container_name: my-astro-app
    restart: unless-stopped
    volumes:
      - .:/workspace
      - ./public/WebApp:/workspace/public/WebApp:ro
      - /workspace/node_modules
    working_dir: /workspace
    command: sh -c "npm install && npm run build && npm run preview -- --host 0.0.0.0"
    ports:
      - "4321:4321"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=appunti_db
      - DB_USER=ninja
      - DB_PASSWORD=Orione___
      - WEBAPP_PATH=/workspace/public/WebApp
    networks:
      - proxy_net
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb:11
    container_name: my-astro-db
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: appunti_db
      MARIADB_ROOT_PASSWORD: Orione___
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - proxy_net
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: my-astro-adminer
    restart: unless-stopped
    ports:
      - "8089:8080"
    networks:
      - proxy_net
    depends_on:
      - db

networks:
  proxy_net:
    external: true
    name: proxy_net

volumes:
  db_data: